trigger:
  - main

pool:
  'Strubli Pool'

stages:

  - stage: 'Prepare'
    displayName: 'Prepare'

    jobs:
      - job: checkout
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
      - job: 'Build'
        pool:
          'Strubli Pool'
        steps:
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: 'github.com'
              sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEQzfLVTh6h3AlVouLg00UVIhB2vPBkqtKSf7uvRpVG1Z2q3c4xXdbQJANh8ToD8yqxFmpGQtLl3NlQguOMx+wq63+gPiWGAq+b5PrQbIN4gpC6fH35AhMztdxNCPpCym891RBYpMny4SKu2tdzfdmhUPQ8exdAYfaBdgOMqb91JfEuVwNCgsOispfayybiH+vIeHOjm9urgzl/pRq+ysf/b8Ow96pCNs1KewOi0hwYP8upcYZvr2cq/FfWEx3D8Gv+9JMueMZDhUxCE0EuhmFS+kmogiqK7l0DvbiYmV6esi8IeCuvWd8uA7OYT4JXSNq9SnVACx2KhVyk3zwG/GIPLjLT0pWgfzS5F9aUSEvtb9E7OIDb79gE3uMoebjb0+DjPoWpIrcspVUDRyzh71R+3xD5bcH1zhfhuXzzJ2VV7xYR9srwOnDuDvxM7rrfoia/qvcmNAdy/TordkeiK+7FH0wzzLbnGkIrXg4ei4DDYs/cYS24MKKMKsIoPgL7+c= leon@Taschenrechner'
              sshKeySecureFile: 'azure_rsa'
          - script: |
              echo $(System.AccessToken)
              echo "---"
              git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" \
                  submodule update --init --recursive
            displayName: Fetch Submodules
          - script: |
              sed -i -e "s/2023-01-01T00:00:00+0200/$(date '+%Y-%m-%dT%H:%M:%S%z')/g" hugo.yml
            displayName: Insert BuildTimestamp in hugo.yml
          - script: |
              /home/linuxbrew/.linuxbrew/bin/hugo --enableGitInfo
            displayName: 'build hugo site'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/public'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
              verbose: true
          - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: drop

  - stage: 'Deployment'
    displayName: 'Deployment'

    jobs:

      - deployment: Wiki_Server
        displayName: Deployment to Strubli wiki server
        environment:
          name: 'Wiki Server'
          resourceName: 'wiki-server'
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    destinationFolder: '/var/www/html/$(WIKI-NAME)/'
                    cleanDestinationFolder: true
                    overwriteExistingFiles: false
                - script: |
                    curl -H "Content-Type: application/json" -X POST -d  '{ "content": "Deployment for $(WIKI-NAME) triggered.", "embeds": [ { "title": "Wiki page '$(WIKI-NAME)' ✅", "description": "Wiki page '$(WIKI-NAME)' successfully deployed. Build id: $(Build.BuildId) 🥳", "url": "https://dev.azure.com/strubli/Strubli%20Wiki/_build/results?buildId=$(Build.BuildId)" } ] }' https://discord.com/api/webhooks/1155459564880269382/q1MDl_diuZ0Pr8YrP_lVJf8m_lA3Cgp1ZHhlLwGqWausaOnPZ9oJS_2qi5JnHTgfi-S3
