# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages
 
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: self-hosted
    env:
      HUGO_VERSION: 0.114.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Insert BuildTimestamp in hugo.yml
        run: |
          source /home/leon/.profile
          sed -i -e "s/2023-01-01T00:00:00+0200/$(date '+%Y-%m-%dT%H:%M:%S%z')/g" hugo.yml
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          echo $PWD
          echo $(PWD)
          source /home/leon/.profile
          hugo \
            --minify \
            --enableGitInfo \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

  # Deployment job
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: SCP Upload
        # You may pin to the exact commit or the version.
        # uses: betanzos/scp-upload@6681a6d4596e23b96314c6c4ae2c154d4c4d346c
        uses: betanzos/scp-upload@v1
        with:
          # Source local file path
          source: public/
          # Remote host
          host: 10.10.0.45
          # Remote host username
          username: leon
          # SSH private key
          key: /home/leon/.ssh/id_rsa #${{ secrets.DEPLOY_AGENT_KEY }}
          # Remote directory to copy the file
          remote_dir: /var/www/html/webfr
          recursive: true
